version: '3.5'

services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=superMYQLUserPwd
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: abm-network
